choco install -y 7zip
choco install -y azure-cli 
choco install -y azure-functions-core-tools --params="'/x64:true'"
choco install -y bicep 
choco install -y chocolateygui 
choco install -y docker-desktop 
choco install -y dotnetcore 
choco install -y git 
choco install -y github-desktop 
choco install -y imgburn 
choco install -y microsoftazurestorageexplorer 
choco install -y notepadplusplus
choco install -y obs-studio 
choco install -y paint.net
choco install -y postman 
choco install -y putty
choco install -y servicebusexplorer 
choco install -y soapui 
choco install -y streamdeck 
choco install -y terraform 
choco install -y vlc 
choco install -y vmware-horizon-client 
choco install -y vscode 
choco install -y winmerge 
choco install -y winscp
choco install -y PDFXchangeEditor
choco install -y python
